---
version: "3"

includes:
  docker: docker/Taskfile.yml

tasks:
  default:
    desc: "Run everything"
    cmds:
      - task: fix
      - task: install
      - task: test

  test:
    desc: "Test task-ui"
    cmds:
      - CGO_ENABLED=1 go test -race -count=1 -cover ./...
      - CGO_ENABLED=0 go test -count=1 -cover ./...

  run:
    desc: "Run task-ui"
    cmds:
      - task-ui --history-enable

  install:
    desc: "Install task-ui"
    cmds:
      - CGO_ENABLED=0 go install .

  fix:
    desc: "Fix code"
    deps:
      - deps:goimports
    cmds:
      - goimports -w .
      - go fmt ./...
      - go vet .
      - go mod tidy
      - ./README.md.sh > README.md

  deps:goimports:
    internal: true
    status:
      - type goimports
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
